// default package
// Generated Feb 8, 2017 8:50:02 AM by Hibernate Tools 5.2.0.CR1
package main.java.model;
import java.util.HashSet;
import java.util.Set;

/**
 * Account generated by hbm2java
 */
public class Account implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int accountId;
	private Double balance;
	private String accountName;
	private Set<User> users = new HashSet<User>(0);

	public Account() {
	}

	public Account(int accountId) {
		this.accountId = accountId;
	}

	public Account(int accountId, Double balance, String accountName, Set<User> users) {
		this.accountId = accountId;
		this.balance = balance;
		this.accountName = accountName;
		this.users = users;
	}

	public int getAccountId() {
		return this.accountId;
	}

	public void setAccountId(int accountId) {
		this.accountId = accountId;
	}

	public Double getBalance() {
		return this.balance;
	}

	public void setBalance(Double balance) {
		this.balance = balance;
	}

	public String getAccountName() {
		return this.accountName;
	}

	public void setAccountName(String accountName) {
		this.accountName = accountName;
	}

	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

}
