package main.java.model;
// default package
// Generated Feb 9, 2017 11:38:22 PM by Hibernate Tools 5.2.0.CR1

import java.util.HashSet;
import java.util.Set;

import com.jfoenix.controls.datamodels.treetable.RecursiveTreeObject;

import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * Stock generated by hbm2java
 */
public class Stock extends RecursiveTreeObject<Stock> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Transaction transaction;
	private String stockName;
	private String stockCode;
	private double price;
	private double previousPrice;
	private Set<UserStock> userStocks = new HashSet<UserStock>(0);
	private StockDetail stockDetail;
	
	private StringProperty stockBuy;
	public Stock() {
	}

	public Stock(Transaction transaction, String stockName, String stockCode, double price, double previousPrice) {
		this.transaction = transaction;
		this.stockName = stockName;
		this.stockCode = stockCode;
		this.price = price;
		this.previousPrice = previousPrice;
	}

	public Stock(Transaction transaction, String stockName, String stockCode, double price, double previousPrice,
	        Set<UserStock> userStocks, StockDetail stockDetail) {
		this.transaction = transaction;
		this.stockName = stockName;
		this.stockCode = stockCode;
		this.price = price;
		this.previousPrice = previousPrice;
		this.userStocks = userStocks;
		this.stockDetail = stockDetail;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Transaction getTransaction() {
		return this.transaction;
	}

	public void setTransaction(Transaction transaction) {
		this.transaction = transaction;
	}

	public String getStockName() {
		return this.stockName;
	}

	public void setStockName(String stockName) {
		this.stockName = stockName;
	}

	public String getStockCode() {
		return this.stockCode;
	}

	public void setStockCode(String stockCode) {
		this.stockCode = stockCode;
	}

	public Double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public double getPreviousPrice() {
		return this.previousPrice;
	}

	public void setPreviousPrice(double previousPrice) {
		this.previousPrice = previousPrice;
	}

	public Set<UserStock> getUserStocks() {
		return this.userStocks;
	}

	public void setUserStocks(Set<UserStock> userStocks) {
		this.userStocks = userStocks;
	}

	public StockDetail getStockDetail() {
		return this.stockDetail;
	}

	public void setStockDetail(StockDetail stockDetail) {
		this.stockDetail = stockDetail;
	}
	
	public StringProperty getStockBuy() {
		return this.stockBuy;
	}
	
	public void setStockBuy(String stockBuy) {
		this.stockBuy = new SimpleStringProperty(stockBuy);
	}
}
