package main.java.model;
// default package
// Generated Feb 9, 2017 11:38:22 PM by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Transaction generated by hbm2java
 */
public class Transaction implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Account account;
	private Date transactionDate;
	private Set<Stock> stocks = new HashSet<Stock>(0);

	public Transaction() {
	}

	public Transaction(Account account, Date transactionDate) {
		this.account = account;
		this.transactionDate = transactionDate;
	}

	public Transaction(Account account, Date transactionDate, Set<Stock> stocks) {
		this.account = account;
		this.transactionDate = transactionDate;
		this.stocks = stocks;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	public Date getTransactionDate() {
		return this.transactionDate;
	}

	public void setTransactionDate(Date transactionDate) {
		this.transactionDate = transactionDate;
	}

	public Set<Stock> getStocks() {
		return this.stocks;
	}

	public void setStocks(Set<Stock> stocks) {
		this.stocks = stocks;
	}
}
