// default package
// Generated Feb 8, 2017 8:50:02 AM by Hibernate Tools 5.2.0.CR1
package main.java.model;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Transaction generated by hbm2java
 */
public class Transaction implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int transactionId;
	private User user;
	private Date datetime;
	private Set<Stock> stocks = new HashSet<Stock>(0);

	public Transaction() {
	}

	public Transaction(int transactionId, User user) {
		this.transactionId = transactionId;
		this.user = user;
	}

	public Transaction(int transactionId, User user, Date datetime, Set<Stock> stocks) {
		this.transactionId = transactionId;
		this.user = user;
		this.datetime = datetime;
		this.stocks = stocks;
	}

	public int getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(int transactionId) {
		this.transactionId = transactionId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Date getDatetime() {
		return this.datetime;
	}

	public void setDatetime(Date datetime) {
		this.datetime = datetime;
	}

	public Set<Stock> getStocks() {
		return this.stocks;
	}

	public void setStocks(Set<Stock> stocks) {
		this.stocks = stocks;
	}

}
