package main.java.model;

import java.math.BigDecimal;

// default package
// Generated Feb 9, 2017 11:38:22 PM by Hibernate Tools 5.2.0.CR1

/**
 * UserStock generated by hbm2java
 */
public class UserStock implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private UserStockId id;
	private Stock stock;
	private User user;
	private BigDecimal combinedValueThreshold;
	private BigDecimal netProfitThreshold;

	public UserStock() {
	}

	public UserStock(UserStockId id, Stock stock, User user) {
		this.id = id;
		this.stock = stock;
		this.user = user;
		this.combinedValueThreshold = new BigDecimal(-1);
		this.netProfitThreshold = new BigDecimal(-1);
	}

	public UserStock(UserStockId id, Stock stock, User user, BigDecimal combinedValueThreshold, BigDecimal netProfitThreshold) {
		this.id = id;
		this.stock = stock;
		this.user = user;
		this.combinedValueThreshold = combinedValueThreshold;
		this.netProfitThreshold = netProfitThreshold;
	}

	public UserStockId getId() {
		return this.id;
	}

	public void setId(UserStockId id) {
		this.id = id;
	}

	public Stock getStock() {
		return this.stock;
	}

	public void setStock(Stock stock) {
		this.stock = stock;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public BigDecimal getCombinedValueThreshold() {
		return this.combinedValueThreshold;
	}

	public void setCombinedValueThreshold(BigDecimal combinedValueThreshold) {
		this.combinedValueThreshold = combinedValueThreshold;
	}

	public BigDecimal getNetProfitThreshold() {
		return this.netProfitThreshold;
	}

	public void setNetProfitThreshold(BigDecimal netProfitThreshold) {
		this.netProfitThreshold = netProfitThreshold;
	}
}
