package main.java.model;
// default package
// Generated Feb 9, 2017 11:38:22 PM by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import main.java.utility.SecurityUtils;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String username;
	private String password;
	private String firstName;
	private String lastName;
	private String email;
	private int alertTime;
	private int stockUpdateTime;
	private String phoneNumber;
	private Date birthday;
	private Account account;
	private Set<UserStock> userStocks = new HashSet<UserStock>(0);
	
	final int DEFAULT_STOCK_UPDATE_TIME = 2;
	final int DEFAULT_ALERT_TIME = 30;

	public User() {
	}

	public User(String username, String password, String firstName, String lastName, String email, String phoneNumber, Date birthday) {
		this.username = username;
		this.setPassword(password);
//		this.password = password;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		setPhoneNumber(phoneNumber);
		this.birthday = birthday;
		alertTime = DEFAULT_ALERT_TIME;
		stockUpdateTime = DEFAULT_STOCK_UPDATE_TIME;
	}

	public User(String username, String password, String firstName, String lastName, String email, String phoneNumber, Date birthday,
			Account account, Set<UserStock> userStocks) {
		this(username, password, firstName, lastName, email, phoneNumber, birthday);
		this.account = account;
		this.userStocks = userStocks;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		// Can't hash directly in this method because when Hibernate execute database query,
		// it will call this method again. Therefore, password will be hashed again as well
		// Workaround: Only hash when current password if different from hashed one
		if (this.password != password)
			password = SecurityUtils.hash(password);
		this.password = password;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public Set<UserStock> getUserStocks() {
		return this.userStocks;
	}

	public void setUserStocks(Set<UserStock> userStocks) {
		this.userStocks = userStocks;
	}

	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}
	
	public void setAlertTime(int alertTime) {
		this.alertTime = alertTime;
	}
	
	public int getAlertTime() {
		return alertTime;
	}
	
	/**
	 * @return the stockUpdateTime
	 */
	public int getStockUpdateTime() {
		return stockUpdateTime;
	}

	/**
	 * @param stockUpdateTime the stockUpdateTime to set
	 */
	public void setStockUpdateTime(int stockUpdateTime) {
		this.stockUpdateTime = stockUpdateTime;
	}

	/**
	 * @return the phoneNumber
	 */
	public String getPhoneNumber() {
		return phoneNumber;
	}

	/**
	 * @param phoneNumber the phoneNumber to set
	 */
	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber.replaceAll("-", "");
	}

	@Override
	public String toString() {
		String userToString = "User instance: \n" + 
							"id: " + this.id + "\n" +
							"username: " + this.username + "\n" +
							"first name: " + this.firstName + "\n" +
							"last name: " + this.lastName + "\n" +
							"email: " + this.email + "\n" +
							"dob: " + this.birthday + "\n" +
							"alert time: " + this.alertTime + "\n" + 
							"stock update time: " + this.stockUpdateTime + "\n";
		return userToString;
	}

}
