-- MySQL Script generated by MySQL Workbench
-- Mon Apr 10 19:57:12 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema stock
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `stock` ;

-- -----------------------------------------------------
-- Schema stock
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stock` DEFAULT CHARACTER SET utf8 ;
USE `stock` ;

-- -----------------------------------------------------
-- Table `stock`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stock`.`user` ;

CREATE TABLE IF NOT EXISTS `stock`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(45) NULL,
  `birthday` DATETIME NOT NULL,
  `alert_time` INT NULL,
  `stock_update_time` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stock`.`stock`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stock`.`stock` ;

CREATE TABLE IF NOT EXISTS `stock`.`stock` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `stock_name` VARCHAR(45) NOT NULL,
  `stock_code` VARCHAR(45) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `previous_price` DECIMAL(10,2) NOT NULL,
  `amount` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `stock_id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stock`.`account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stock`.`account` ;

CREATE TABLE IF NOT EXISTS `stock`.`account` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `balance` DOUBLE NOT NULL,
  `account_name` VARCHAR(45) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  UNIQUE INDEX `account_id_UNIQUE` (`id` ASC),
  INDEX `fk_account_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_account_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `stock`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stock`.`transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stock`.`transaction` ;

CREATE TABLE IF NOT EXISTS `stock`.`transaction` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `transaction_date` DATETIME NOT NULL,
  `account_id` INT NOT NULL,
  `payment` DOUBLE NULL,
  `balance` DOUBLE NULL,
  `stock_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `transaction_id_UNIQUE` (`id` ASC),
  INDEX `fk_transaction_account1_idx` (`account_id` ASC),
  INDEX `fk_transaction_stock1_idx` (`stock_id` ASC),
  CONSTRAINT `fk_transaction_account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `stock`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transaction_stock1`
    FOREIGN KEY (`stock_id`)
    REFERENCES `stock`.`stock` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stock`.`stock_detail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stock`.`stock_detail` ;

CREATE TABLE IF NOT EXISTS `stock`.`stock_detail` (
  `stock_id` INT NOT NULL,
  `company_name` VARCHAR(45) NULL,
  `company_description` VARCHAR(45) NULL,
  `listed_date` DATETIME NULL,
  `remark` VARCHAR(45) NULL,
  PRIMARY KEY (`stock_id`),
  INDEX `fk_stock_detail_stock1_idx` (`stock_id` ASC),
  CONSTRAINT `fk_stock_detail_stock1`
    FOREIGN KEY (`stock_id`)
    REFERENCES `stock`.`stock` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stock`.`user_stock`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stock`.`user_stock` ;

CREATE TABLE IF NOT EXISTS `stock`.`user_stock` (
  `stock_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `value_threshold` DECIMAL(10,0) NULL,
  `combined_value_threshold` DECIMAL(10,0) NULL,
  `net_profit_threshold` DECIMAL(10,0) NULL,
  `stock_type` INT NULL,
  PRIMARY KEY (`stock_id`, `user_id`),
  INDEX `fk_stock_has_user_user1_idx` (`user_id` ASC),
  INDEX `fk_stock_has_user_stock1_idx` (`stock_id` ASC),
  CONSTRAINT `fk_stock_has_user_stock1`
    FOREIGN KEY (`stock_id`)
    REFERENCES `stock`.`stock` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stock_has_user_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `stock`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
